- .github/workflows/build-docs.yml
- .gitignore
- README.md
- docs/Makefile
- docs/conf.py
- docs/index.rst
- docs/make.bat
- docs/modules.rst
- docs/multiversx_sdk.core.adapters.rst
- docs/multiversx_sdk.core.proto.rst
- docs/multiversx_sdk.core.rst
- docs/multiversx_sdk.core.transaction_builders.rst
- docs/multiversx_sdk.core.transaction_parsers.rst
- docs/multiversx_sdk.core.transactions_factories.rst
- docs/multiversx_sdk.core.transactions_outcome_parsers.rst
- docs/multiversx_sdk.network_providers.rst
- docs/multiversx_sdk.rst
- docs/multiversx_sdk.wallet.crypto.rst
- docs/multiversx_sdk.wallet.libraries.rst
- docs/multiversx_sdk.wallet.rst
- multiversx_sdk/core/account.py
- multiversx_sdk/core/address.py
- pyproject.toml
- requirements-dev.txt
The published docs can be found [here](https://multiversx.github.io/mx-sdk-py-incubator/).
> Publish docs to GH pages

- docs/multiversx_sdk.core.transactions_outcome_parsers.rst
- multiversx_sdk/__init__.py
- multiversx_sdk/converters/transactions_converter.py
- multiversx_sdk/converters/transactions_converter_test.py
- multiversx_sdk/core/__init__.py
- multiversx_sdk/core/transactions_outcome_parsers/__init__.py
- multiversx_sdk/core/transactions_outcome_parsers/resources.py
- multiversx_sdk/core/transactions_outcome_parsers/smart_contract_transactions_outcome_parser.py
- multiversx_sdk/core/transactions_outcome_parsers/smart_contract_transactions_outcome_parser_test.py
- multiversx_sdk/core/transactions_outcome_parsers/smart_contract_transactions_outcome_parser_types.py
- multiversx_sdk/core/transactions_outcome_parsers/token_management_transactions_outcome_parser_test.py
- multiversx_sdk/network_providers/transaction_events.py
- multiversx_sdk/network_providers/transactions.py
- requirements.txt
Implemented the smart contract deploy transactions parser based on the sdk-specs.
> Smart Contract deploy transactions parser

- multiversx_sdk/core/transactions_factories/token_management_transactions_factory.py
- multiversx_sdk/core/transactions_factories/token_management_transactions_factory_test.py
Added missing role according to [this PR](https://github.com/multiversx/mx-sdk-specs/pull/65).
> Added ESDTTransferRole on fungible token

- .github/workflows/build-docs.yml
- .github/workflows/test.yml
- For tests workflow: `macos-latest` is already ARM64
- For docs: do not run on pull requests against `main` anymore
> Adjust workflows (docs, tests)

- examples/Cookbook.ipynb
- multiversx_sdk/__init__.py
- multiversx_sdk/core/__init__.py
- multiversx_sdk/network_providers/__init__.py
- multiversx_sdk/network_providers/transaction_decoder.py
- multiversx_sdk/network_providers/transaction_decoder_test.py
The transaction decoder was in another [repository](https://github.com/multiversx/mx-sdk-py-transaction-decoder) but know it's been slightly updated and moved inside the Python sdk.
> Added transaction decoder

- examples/Cookbook.ipynb
- multiversx_sdk/core/address.py
- multiversx_sdk/core/errors.py
- multiversx_sdk/core/smart_contract_queries_controller.py
- multiversx_sdk/core/smart_contract_queries_controller_test.py
- pyproject.toml
See: https://github.com/multiversx/mx-sdk-specs/pull/68.
Also, un-deprecated `Address.serialize()` - it was deprecated a bit too early (complete replacement not yet in place).
> Query improvements: add SmartContractQueriesController.query()

- multiversx_sdk/network_providers/accounts.py
- multiversx_sdk/network_providers/api_network_provider_test.py
- pyproject.toml
See:
- https://api.multiversx.com/accounts/erd1qqqqqqqqqqqqqpgqvc7gdl0p4s97guh498wgz75k8sav6sjfjlwqh679jy
- https://gateway.multiversx.com/address/erd1qqqqqqqqqqqqqpgqvc7gdl0p4s97guh498wgz75k8sav6sjfjlwqh679jy
`code_hash` and `root_hash` are base64-encoded, which is somehow unfortunate. Their encoding wasn't changed to hex, in order to avoid a breaking change.
> Additional fields on "AccountOnNetwork"

- multiversx_sdk/abi/codec.py
- multiversx_sdk/abi/serializer.py
- multiversx_sdk/abi/serializer_test.py
This can be reviewed side-by-side with:
- https://github.com/multiversx/mx-sdk-abi-go/blob/main/abi/serializer.go
- https://github.com/multiversx/mx-sdk-abi-go/blob/main/abi/serializer_test.go
- https://github.com/multiversx/mx-sdk-abi-go/blob/main/abi/codec.go
> ABI/codecs implementation (part 1)

- multiversx_sdk/abi/abi_definition.py
- multiversx_sdk/testutils/testdata/adder.abi.json
- multiversx_sdk/testutils/testdata/lottery-esdt.abi.json
- multiversx_sdk/testutils/testdata/multisig-full.abi.json
Defines ABI definition concepts, as Python classes.
> Codecs (part 6) - ABI definitions

- multiversx_sdk/core/smart_contract_queries_controller.py
- multiversx_sdk/core/smart_contract_queries_controller_test.py
- multiversx_sdk/core/smart_contract_query.py
- multiversx_sdk/core/transaction.py
- multiversx_sdk/core/transactions_factories/smart_contract_transaction_factory_test.py
- multiversx_sdk/core/transactions_factories/smart_contract_transactions_factory.py
> Codecs (part 7): integration of serializer & ABI into queries controller and contract transactions factory

- multiversx_sdk/abi/address_value.py
- multiversx_sdk/abi/address_value_test.py
- multiversx_sdk/abi/bigint_value.py
- multiversx_sdk/abi/biguint_value.py
- multiversx_sdk/abi/bool_value.py
- multiversx_sdk/abi/bytes_value.py
- multiversx_sdk/abi/bytes_value_test.py
- multiversx_sdk/abi/codec.py
- multiversx_sdk/abi/fields.py
- multiversx_sdk/abi/interface.py
- multiversx_sdk/abi/list_value.py
- multiversx_sdk/abi/list_value_test.py
- multiversx_sdk/abi/option_value.py
- multiversx_sdk/abi/serializer.py
- multiversx_sdk/abi/small_int_values.py
- multiversx_sdk/abi/string_value.py
- multiversx_sdk/abi/string_value_test.py
- multiversx_sdk/abi/tuple_value.py
- multiversx_sdk/abi/typesystem.py
- multiversx_sdk/core/address.py
This brings partial support for converting typed values to native Python objects (and back).
> Codecs (part 9): payload holders - set_value, get_value on some typed values

- multiversx_sdk/abi/enum_value.py
- multiversx_sdk/abi/enum_value_test.py
> Codecs (part 11) - enums: set_value, get_value

- multiversx_sdk/abi/option_value.py
- multiversx_sdk/abi/option_value_test.py
- multiversx_sdk/abi/struct_value.py
- multiversx_sdk/abi/struct_value_test.py
> Codecs (part 12): struct & option - set_payload(), get_payload()

- multiversx_sdk/abi/abi.py
- multiversx_sdk/abi/abi_test.py
- multiversx_sdk/abi/tuple_value.py
- multiversx_sdk/abi/tuple_value_test.py
- multiversx_sdk/testutils/testdata/artificial.abi.json
Changes:
- Define the `Abi` component, able to encode & decode endpoint parameters. When the component is initialized, it reads the ABI definitions and prepares value prototypes (typed values) for endpoint parameters & custom types. Then, when appropriate, it clones these prototypes and populates them with native Python values / gets Python values out of them.
- Add missing tests for tuples etc.
> Codecs (part 14): abi-based encoding & decoding

- multiversx_sdk/abi/serializer.py
- multiversx_sdk/abi/serializer_test.py
Now raising an `Exception` if not all provided bytes have been deserialized when decoding values into `TypedValues`.
> Ensure all bytes are deserialized

- multiversx_sdk/wallet/user_signer.py
- multiversx_sdk/wallet/user_test.py
We were able to load multiple `UserPEM`s from file but not multiple `UserSigner`s.
> Load multiple signers from pem file

- multiversx_sdk/abi/struct_value.py
- multiversx_sdk/abi/struct_value_test.py
There was a small bug, the first value of the list was skipped resulting in an error.
> Fixed set payload from list

- multiversx_sdk/abi/address_value.py
- multiversx_sdk/abi/address_value_test.py
- multiversx_sdk/abi/bytes_value.py
- multiversx_sdk/abi/bytes_value_test.py
- multiversx_sdk/abi/shared.py
- multiversx_sdk/abi/shared_test.py
- pyproject.toml
Previously, the `AddresValue` used to convert the value of `set_payload` to `bytes`. Added support to set payload from a `dictionary` like bellow:
```py
AddressValue.set_payload(
{
"bech32": "erd1qyu5wthldzr8wx5c9ucg8kjagg0jfs53s8nr3zpz3hypefsdd8ssycr6th"
}
)
```
or
```py
AddressValue.set_payload(
{
"hex": "0139472eff6886771a982f3083da5d421f24c29181e63888228dc81ca60d69e1"
}
)
```
`BytesValue` can now be set from a `hex` string, like so:
```py
BytesValue.set_payload(
{
"hex": "68656c6c6f"
}
)
```
Also now, an error is raised if someone tries to convert a `dictionary` to a `list` using `convert_native_value_to_list`.
> Support for instantiating address and bytes values from dictionary

- multiversx_sdk/core/interfaces.py
- multiversx_sdk/core/tokens.py
- multiversx_sdk/core/transactions_factories/smart_contract_transactions_factory.py
- multiversx_sdk/core/transactions_factories/token_transfers_data_builder.py
- multiversx_sdk/core/transactions_factories/transfer_transactions_factory.py
- pyproject.toml
- Refactoring: Pass `Token` & `TokenTransfer` as concrete classes (since they are mere DTOs), instead as of an interface
- `IToken`, `ITokenTransfer` and `ITokenIdentifierParts` have been removed - this is a small breaking change of the public API
- Related to https://github.com/multiversx/mx-sdk-specs/pull/76.
> Minor breaking change: pass "Token" & "TokenTransfer" as concrete classes, instead as of interfaces

- multiversx_sdk/core/transactions_outcome_parsers/transaction_events_parser_test.py
- multiversx_sdk/network_providers/transaction_decoder.py
- multiversx_sdk/network_providers/transaction_decoder_test.py
The fix was done accordingly to [this PR](https://github.com/multiversx/mx-sdk-js-transaction-decoder/pull/13).
> Do not remove function_name & function_args if no args but receiver is smart contract

- multiversx_sdk/abi/abi.py
- multiversx_sdk/core/transactions_outcome_parsers/transaction_events_parser_test.py
- multiversx_sdk/network_providers/transaction_events.py
- pyproject.toml
Sometimes, these fields can be null:
- `event.additionalData`
- `event.topics`
Generally speaking, they should be arrays.
Additional minor fix on ABI (`I64Value` wasn't properly handled before).
> Handle "null" values on event fields (they happen sometimes)

- .flake8
- multiversx_sdk/abi/abi.py
- multiversx_sdk/abi/serializer_test.py
- multiversx_sdk/core/transaction_test.py
- multiversx_sdk/core/transactions_factories/transfer_transactions_factory.py
- multiversx_sdk/core/transactions_outcome_parsers/transaction_events_parser.py
- multiversx_sdk/core/typecheck.py
- multiversx_sdk/network_providers/network_config.py
- multiversx_sdk/network_providers/transaction_decoder.py
- multiversx_sdk/wallet/libraries/bls_facade_test.py
- multiversx_sdk/wallet/validator_test.py
Renamed a parameter:
From: 
```py
def decode_event(self, event_name: str, topics: List[bytes], data_items: List[bytes]) -> SimpleNamespace:
```
To:
```py
def decode_event(self, event_name: str, topics: List[bytes], additional_data: List[bytes]) -> SimpleNamespace:
```
> Renamed method parameter and fixed linter issue

- multiversx_sdk/abi/__init__.py
- multiversx_sdk/abi/abi.py
- multiversx_sdk/abi/code_metadata_value.py
- multiversx_sdk/abi/code_metadata_value_test.py
- multiversx_sdk/core/code_metadata.py
- multiversx_sdk/core/code_metadata_test.py
Previously, `CodeMetadata` was handled as `bytes` - this was incorrect, since the encoding is different (code metadata has a fixed size of two bytes).
> ABI: handle CodeMetadataValue

- multiversx_sdk/abi/__init__.py
- multiversx_sdk/abi/abi.py
- multiversx_sdk/abi/abi_definition.py
- multiversx_sdk/abi/abi_test.py
- multiversx_sdk/abi/enum_value.py
- multiversx_sdk/abi/enum_value_test.py
- multiversx_sdk/abi/explicit_enum_value.py
- multiversx_sdk/testutils/testdata/artificial.abi.json
- pyproject.toml
Implement explicit enums e.g.:
```
"OperationCompletionStatus": {
"type": "explicit-enum",
"variants": [
{
"docs": [
"indicates that operation was completed"
],
"name": "completed"
},
{
"docs": [
"indicates that operation was interrupted prematurely, due to low gas"
],
"name": "interrupted"
}
]
},
```
References:
- https://github.com/multiversx/mx-sdk-js-core/issues/519
- https://github.com/multiversx/mx-sdk-rs/pull/1113
> Implement explicit enums

- multiversx_sdk/controllers/delegation_controller.py
- multiversx_sdk/controllers/interfaces.py
- multiversx_sdk/controllers/relayed_controller.py
- multiversx_sdk/controllers/smart_contract_controller.py
- multiversx_sdk/controllers/token_management_controller.py
Move `INetworkProvider` and `IAbi` to `controllers/interfaces.py`.
Even further, perhaps directly receive `Abi` instead of `IAbi` (to be discussed).
> Move "INetworkProvider" and "IAbi" to controllers/interfaces.py

- multiversx_sdk/core/transactions_factories/transfer_transactions_factory.py
- multiversx_sdk/core/transactions_factories/transfer_transactions_factory_test.py
- pyproject.toml
Previously, if a single  `EGLD` token transfer was provided, the `ESDTTransfer` builtin function was used and the transaction would fail, as this operation is not allowed. `EGLD` can only be transferred using the `MultiESDTNFTTransfer` builtin function.
> Fix for single EGLD transfer as token transfer

- multiversx_sdk/core/tokens.py
- multiversx_sdk/core/tokens_test.py
- multiversx_sdk/core/transactions_factories/transfer_transactions_factory_test.py
Added support for ESDT token prefix. Used for tokens created on sovereign chains.
> Added support for tokens prefix

- multiversx_sdk/core/address.py
- multiversx_sdk/core/address_test.py
- multiversx_sdk/core/tokens.py
- multiversx_sdk/core/transaction_on_network.py
- multiversx_sdk/core/transactions_outcome_parsers/delegation_transactions_outcome_parser_test.py
- multiversx_sdk/core/transactions_outcome_parsers/smart_contract_transactions_outcome_parser.py
- multiversx_sdk/core/transactions_outcome_parsers/smart_contract_transactions_outcome_parser_test.py
- multiversx_sdk/core/transactions_outcome_parsers/token_management_transactions_outcome_parser_test.py
- multiversx_sdk/core/transactions_outcome_parsers/transaction_events_parser_test.py
- multiversx_sdk/network_providers/api_network_provider.py
- multiversx_sdk/network_providers/api_network_provider_test.py
- multiversx_sdk/network_providers/http_resources.py
- multiversx_sdk/network_providers/proxy_network_provider.py
- multiversx_sdk/network_providers/proxy_network_provider_test.py
- multiversx_sdk/network_providers/transaction_awaiter.py
- multiversx_sdk/network_providers/transaction_awaiter_test.py
- multiversx_sdk/network_providers/transaction_decoder.py
- multiversx_sdk/network_providers/transaction_decoder_test.py
- multiversx_sdk/testutils/mock_network_provider.py
- multiversx_sdk/testutils/mock_transaction_on_network.py
Updated the `TransactionOnNetwork` class to match the [specs](https://github.com/multiversx/mx-sdk-specs/blob/main/core/transaction_on_network.md).
> Update TransactionOnNetwork to specs

- multiversx_sdk/converters/transactions_converter.py
- multiversx_sdk/core/transactions_outcome_parsers/smart_contract_transactions_outcome_parser_test.py
- multiversx_sdk/network_providers/transaction_events.py
- pyproject.toml
The `TransactionEvent`'s data field has been changed to `bytes` from `string` as it could contain complex structures that could not be easily decoded.
Should fix this issue https://github.com/multiversx/mx-sdk-py/issues/158.
> Changed data field to bytes

- docs/conf.py
- docs/multiversx_sdk.abi.rst
- docs/multiversx_sdk.core.rst
- docs/multiversx_sdk.network_providers.rst
- examples/Cookbook.ipynb
- multiversx_sdk/__init__.py
- multiversx_sdk/core/__init__.py
- multiversx_sdk/core/address.py
- multiversx_sdk/core/address_test.py
- multiversx_sdk/core/config.py
- multiversx_sdk/core/constants.py
- multiversx_sdk/core/transaction_builders/default_configuration.py
- multiversx_sdk/core/transaction_builders/relayed_v1_builder.py
- multiversx_sdk/core/transactions_factories/delegation_transactions_factory.py
- multiversx_sdk/core/transactions_factories/delegation_transactions_factory_test.py
- multiversx_sdk/core/transactions_factories/smart_contract_transaction_factory_test.py
- multiversx_sdk/core/transactions_factories/smart_contract_transactions_factory.py
- multiversx_sdk/core/transactions_factories/transactions_factory_config.py
- multiversx_sdk/core/transactions_outcome_parsers/delegation_transactions_outcome_parser.py
- multiversx_sdk/core/transactions_outcome_parsers/smart_contract_transactions_outcome_parser.py
- multiversx_sdk/core/transactions_outcome_parsers/token_management_transactions_outcome_parser.py
- multiversx_sdk/network_providers/api_network_provider.py
- multiversx_sdk/network_providers/constants.py
- multiversx_sdk/network_providers/proxy_network_provider.py
- multiversx_sdk/network_providers/transactions.py
- multiversx_sdk/wallet/user_keys.py
- multiversx_sdk/wallet/user_wallet.py
- pyproject.toml
Added a `LibraryConfig` that stores the default `hrp` value.
> Added library config

- multiversx_sdk/wallet/errors.py
- multiversx_sdk/wallet/interfaces.py
- multiversx_sdk/wallet/user_keys.py
- multiversx_sdk/wallet/user_signer.py
- multiversx_sdk/wallet/user_test.py
- multiversx_sdk/wallet/user_verifer.py
- multiversx_sdk/wallet/validator_keys.py
- multiversx_sdk/wallet/validator_signer.py
- multiversx_sdk/wallet/validator_verifier.py
- Specs [UserSecretKey](https://github.com/multiversx/mx-sdk-specs/blob/main/wallet/secret_key.md)
- Specs [UserPublicKey](https://github.com/multiversx/mx-sdk-specs/blob/main/wallet/public_key.md)
> Update user keys to specs

- multiversx_sdk/abi/address_value.py
- multiversx_sdk/abi/address_value_test.py
Currently, bech32 string cannot be directly passed as tranaction argument to the smart-contract factories. Indeed, this leads to an error when setting the payload of an AddressValue
```python
AddressValue().set_payload("erd1qyu5wthldzr8wx5c9ucg8kjagg0jfs53s8nr3zpz3hypefsdd8ssycr6th")
def set_payload(self, value: Any):
if isinstance(value, dict):
value = cast(Dict[str, str], value)
pubkey = self._extract_pubkey_from_dict(value)
else:
>           pubkey = bytes(value)
E           TypeError: string argument without an encoding
multiversx_sdk/abi/address_value.py:52: TypeError
```
If the `set_payload` method receives a string, it should try to parse it as bech32 to extract the pubkey
```python
def set_payload(self, value: Any):
if isinstance(value, dict):
value = cast(Dict[str, str], value) …
```
> Allow bech32 address value payload

- .github/workflows/ci.yml
- multiversx_sdk/ledger/ledger_app.py
- pyproject.toml
Now, when the package is installed without the optional dependency it displays an error message when used:
```py
ImportError: The ledgercomm package is not installed. Please install it using pip install multiversx_sdk[ledger].
```
Also updated the upload artifact to **v4** according to this [blog post](https://github.blog/changelog/2024-04-16-deprecation-notice-v3-of-the-artifact-actions/).
> Fix optional dependency import

- multiversx_sdk/abi/abi.py
- multiversx_sdk/abi/abi_test.py
- multiversx_sdk/testutils/testdata/artificial.abi.json
BigInt prototypes were wrongly constructed as `BigUIntValue`
Replace `BigUIntValue` by `BigIntValue` and add tests to cover this case
> Fix wrong bigint prototype

- multiversx_sdk/abi/abi_test.py
- multiversx_sdk/abi/enum_value.py
- multiversx_sdk/abi/enum_value_test.py
- multiversx_sdk/core/transaction_events_parser_test.py
When a user do a query while providing an ABI and expectes an enum as a result, he will receive the discriminant of the variant of the Enum. This is not very user friendly as the variant are originally defined by name.
When the `names_to_discriminants` dict is available in the `EnumValue` prototype, return also the name of the variant in the payload.
This allow to go from `{__discriminant__=43, e=5, f=6}` to `{__discriminant__=43, __name__="TypeC", e=5, f=6}`
> Add name in enum payload

- multiversx_sdk/core/tokens.py
- multiversx_sdk/core/tokens_test.py
Currently the classses `Token` and `TokenTransfer` cannot be compared
```python
>>>Token("NFT-123456", 777) == Token("NFT-123456", 777)
False
```
and they are displayed as object
```python
>>>print(Token("NFT-123456", 777))
<multiversx_sdk.core.tokens.Token object at 0x75c4c8349550>
```
implement `__eq__` and `__str__` for `Token` and `TokenTransfer`
> Add eq and str for token

- docs/conf.py
- multiversx_sdk/account_management/account_controller.py
- multiversx_sdk/core/base_controller.py
- multiversx_sdk/core/base_controller_test.py
- multiversx_sdk/delegation/delegation_controller.py
- multiversx_sdk/relayed/relayed_controller.py
- multiversx_sdk/smart_contracts/smart_contract_controller.py
- multiversx_sdk/token_management/token_management_controller.py
- multiversx_sdk/transfers/transfers_controller.py
- multiversx_sdk/validators/validators_controller.py
- multiversx_sdk/validators/validators_controller_test.py
- pyproject.toml
The `transactions options` were not properly set when creating guarded transactions using the controllers.
Also, added a new guardian argument for `create_transaction_for_setting_guardian()`.
> Set correct options for guarded transactions

- multiversx_sdk/network_providers/api_network_provider.py
- multiversx_sdk/network_providers/api_network_provider_test.py
- multiversx_sdk/network_providers/proxy_network_provider.py
- multiversx_sdk/network_providers/proxy_network_provider_test.py
If the same `NetworkProviderConfig` was used to instantiate multiple network providers, `User-Agent` used to duplicate for each network provider. Now, we don't alter the config anymore.
> Fix duplication of user agent

- .github/workflows/build-docs.yml
The workflow pushes to the `gh-pages` branch, thus it needs write permission.
> Grant write permission for docs workflow
